[rpc_endpoints]
local = "http://127.0.0.1:8545"
sepolia = "${FORK_URL}"

[profile.scratch]
src = "scratchsrc"
test = "scratch/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level02]
src = "level02/src"
test = "level02/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level03]
src = "level03/src"
test = "level03/test"
out = "out"
libs = ["lib"]
solc = "0.6.5"

[profile.level04]
src = "level04/src"
test = "level04/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level05]
src = "level05/src"
test = "level05/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level06]
src = "level06/src"
test = "level06/test"
out = "out"
libs = ["lib"]
solc = "0.6.5"

[profile.level07]
src = "level07/src"
test = "level07/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level08]
src = "level08/src"
test = "level08/test"
out = "out"
libs = ["lib"]
solc = "0.8.17"

[profile.level09]
src = "level09/src"
test = "level09/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level10]
src = "level10/src"
test = "level10/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level11]
src = "level11/src"
test = "level11/test"
out = "out"
libs = ["lib"]
solc = "0.6.12"

[profile.level12]
src = "level12/src"
test = "level12/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level13]
src = "level13/src"
test = "level13/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level14]
src = "level14/src"
test = "level14/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level15]
src = "level15/src"
test = "level15/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level16]
src = "level16/src"
test = "level16/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level17]
src = "level17/src"
test = "level17/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.level18]
src = "level18/src"
test = "level18/test"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config